import express from 'express';
// import cashfreeWebHook from './cashfree/index.js';
// import zenTechIndWebhook from './zenTechInd/index.js';
import tryCatchHandler from '../../utils/tryCatchHandler.js';
import { cashfreeWebHook } from './cashfree.js';
import { zenTechIndWebhook } from './zenTechInd.js';
import { clickrrWebhook } from './clickrr.js';
import { nmplPayWebhook } from './nmplPay.js';
import { silkPayWebhook } from './silkPay.js';
import { handleRazorpayWebhook } from './razorPay.js';    
import { rupeeFlowWebhook } from './rupeeflow.js';
import { orvixPayWebhook } from './orvixPay.js';
import { runsafeWebhook } from './runsafe.js';
import { cpsWebhook } from './cps.js';
import { payEasyWebhook } from './payeasy.js';
import { payEasy02Webhook } from './payeasy02.js';
import { payEasy03Webhook } from './payeasy03.js';
import { tytlWebhook } from "./tytl.js";
import { albeCollectWebhook } from './albeCollect.js';
import { pennyPayWebhook } from './pennypay.js';
import { freechipsWebhook } from './freeChips.js';
import { payinIpAccessControl } from '../../middlewares/ipAccessControl.js';

const router = express.Router();

router.post('/cashfree', payinIpAccessControl, tryCatchHandler(cashfreeWebHook));
router.post('/zenTechInd', payinIpAccessControl, tryCatchHandler(zenTechIndWebhook));
router.post('/nmplPay', payinIpAccessControl, tryCatchHandler(nmplPayWebhook));
router.post('/runsafe', payinIpAccessControl, tryCatchHandler(runsafeWebhook));
router.post('/cps', payinIpAccessControl, tryCatchHandler(cpsWebhook));
router.post('/silkPay', payinIpAccessControl, tryCatchHandler(silkPayWebhook));
router.post('/tytl', payinIpAccessControl, tryCatchHandler(tytlWebhook));
router.post('/clickrr', payinIpAccessControl, tryCatchHandler(clickrrWebhook)); 
router.post('/razorpay', payinIpAccessControl, tryCatchHandler(handleRazorpayWebhook));
router.post('/rupeeflow', payinIpAccessControl, tryCatchHandler(rupeeFlowWebhook));
router.post('/orvixPay', payinIpAccessControl, tryCatchHandler(orvixPayWebhook));
router.post('/payeasy', payinIpAccessControl, tryCatchHandler(payEasyWebhook));
router.post('/payeasy02', payinIpAccessControl, tryCatchHandler(payEasy02Webhook));
router.post('/payeasy03', payinIpAccessControl, tryCatchHandler(payEasy03Webhook));
router.post('/albeCollect', payinIpAccessControl, tryCatchHandler(albeCollectWebhook));
router.post('/paynow', payinIpAccessControl, tryCatchHandler(pennyPayWebhook));
router.post('/freechips', payinIpAccessControl, tryCatchHandler(freechipsWebhook));

export default router;
