export const Status = {
  ASSIGNED: 'ASSIGNED',
  SUCCESS: 'SUCCESS',
  DROPPED: 'DROPPED',
  DUPLICATE: 'DUPLICATE',
  INITIATED: 'INITIATED',
  DISPUTE: 'DISPUTE',
  REVERSED: 'REVERSED',
  IMG_PENDING: 'IMG_PENDING',
  PENDING: 'PENDING',
  REJECTED: 'REJECTED',
  TEST_SUCCESS: 'TEST_SUCCESS',
  TEST_DROPPED: 'TEST_DROPPED',
  BANK_MISMATCH: 'BANK_MISMATCH',
  FAILED: 'FAILED',
  USER_DROPPED: 'USER_DROPPED',
  APPROVED: 'APPROVED',
  BOT: '/success',
};

export const Currency = {
  INR: 'INR',
};

export const Method = {
  BANK: 'BANK',
  CASH: 'CASH',
  AED: 'AED',
  CRYPTO: 'CRYPTO',
  EKO: 'EKO',
  CLICKRR: 'CLICKRR',
  TATAPAY: 'TATAPAY',
  PAYASSIST: 'PAYASSIST',
  RUPEEFLOW: 'RUPEEFLOW',
  BSS: 'BSS',
  SILKPAY: 'SILKPAY',
  BSS02: 'BSS02',
  BSS03: 'BSS03',
};

export const Type = {
  PAYIN: 'PAYIN',
  PAYOUT: 'PAYOUT',
};

export const Role = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  TRANSACTIONS: 'TRANSACTIONS',
  OPERATIONS: 'OPERATIONS',
  MERCHANT_ADMIN: 'MERCHANT_ADMIN',
  VENDOR_ADMIN: 'VENDOR_ADMIN',
  MERCHANT: 'MERCHANT',
  SUB_MERCHANT: 'SUB_MERCHANT',
  MERCHANT_OPERATIONS: 'MERCHANT_OPERATIONS',
  VENDOR: 'VENDOR',
  SUB_VENDOR: 'SUB_VENDOR',
  VENDOR_OPERATIONS: 'VENDOR_OPERATIONS',
  BOT: 'BOT',
};
export const RoleIs = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MERCHANT: 'MERCHANT',
  VENDOR: 'VENDOR',
  BOT: 'BOT',
};
export const DesignationIs = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  TRANSACTIONS: 'TRANSACTIONS',
  OPERATIONS: 'OPERATIONS',
  MERCHANT_ADMIN: 'MERCHANT_ADMIN',
  VENDOR_ADMIN: 'VENDOR_ADMIN',
  MERCHANT: 'MERCHANT',
  SUB_MERCHANT: 'SUB_MERCHANT',
  MERCHANT_OPERATIONS: 'MERCHANT_OPERATIONS',
  VENDOR: 'VENDOR',
  SUB_VENDOR: 'SUB_VENDOR',
  VENDOR_OPERATIONS: 'VENDOR_OPERATIONS',
  BOT: 'BOT',
};
export const columns = {
  USER_OTP: [
    'id',
    'user_id',
    'is_used',
    'otp',
    'expiration_time',
    'created_at',
    'updated_at',
  ],
  MERCHANT: [
    'id',
    'user_id',
    'first_name',
    'last_name',
    'code',
    'min_payin',
    'max_payin',
    'payin_commission',
    'min_payout',
    'max_payout',
    'payout_commission',
    'is_test_mode',
    'is_enabled',
    'dispute_enabled',
    'is_demo',
    'balance',
    'config',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
    'subMerchants',
  ],
  USER: [
    'id',
    'role_id',
    'designation_id',
    'first_name',
    'last_name',
    'email',
    'contact_no',
    'user_name',
    // 'password',
    'code',
    'is_enabled',
    'last_login',
    'last_logout',
    'config',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
  ],
  ROLE: ['id', 'role', 'created_at', 'updated_at'],
  COMPANY: ['id', 'first_name', 'last_name', 'email', 'contact_no', 'config'],
  SETTLEMENT: [
    'id',
    'sno',
    'user_id',
    'status',
    'amount',
    'method',
    'config',
    'approved_at',
    'rejected_at',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
    // 'company_id',
  ],
  CALCULATION: [
    'id',
    'user_id',
    'total_payin_count',
    'total_payin_amount',
    'total_payin_commission',
    'total_payout_count',
    'total_payout_amount',
    'total_payout_commission',
    'total_settlement_count',
    'total_settlement_amount',
    'total_chargeback_count',
    'total_chargeback_amount',
    'current_balance',
    'net_balance',
    'created_at',
    'updated_at',
    'total_reverse_payout_count',
    'total_reverse_payout_amount',
    'total_reverse_payout_commission',
  ],
  COMPLAINTS: [
    'id',
    'sno',
    'status',
    'payin_id',
    'email',
    'config',
    'created_at',
    'updated_at',
  ],
  DESIGNATION: ['id', 'designation', 'role_id', 'created_at', 'updated_at'],
  PAYIN: [
    'id',
    'sno',
    'upi_short_code',
    'qr_params',
    'amount',
    'status',
    'is_notified',
    'user_submitted_utr',
    'currency',
    'merchant_order_id',
    'user',
    'bank_acc_id',
    'merchant_id',
    'bank_response_id',
    'payin_merchant_commission',
    'payin_vendor_commission',
    'user_submitted_image',
    'duration',
    'is_url_expires',
    'expiration_date',
    'one_time_used',
    'approved_at',
    'failed_at',
    'config',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
  ],
  PAYOUT: [
    'id',
    'sno',
    'user',
    'merchant_id',
    'bank_acc_id',
    'amount',
    'status',
    'failed_reason',
    'currency',
    'merchant_order_id',
    'acc_no',
    'acc_holder_name',
    'ifsc_code',
    'bank_name',
    'upi_id',
    'utr_id',
    'rejected_reason',
    'payout_merchant_commission',
    'payout_vendor_commission',
    'approved_at',
    'rejected_at',
    'config',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
  ],
  BANK_ACCOUNT: [
    'id',
    'sno',
    'user_id',
    'upi_id',
    'upi_params',
    'acc_holder_name',
    'nick_name',
    'acc_no',
    'ifsc',
    'bank_name',
    'is_qr',
    'is_bank',
    'is_enabled',
    'min',
    'max',
    'payin_count',
    'balance',
    'today_balance',
    'bank_used_for',
    'config',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
  ],
  VENDOR: [
    'id',
    'user_id',
    'first_name',
    'last_name',
    'code',
    'payin_commission',
    'payout_commission',
    'balance',
    'created_by',
    'updated_by',
    'config',
    'created_at',
    'updated_at',
    'subVendors',
  ],
  CHARGE_BACK: [
    'id',
    'sno',
    'merchant_user_id',
    'vendor_user_id',
    'payin_id',
    'bank_acc_id',
    'amount',
    'reference_date',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
  ],
  USER_HIERARCHY: [
    'id',
    'config',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
  ],
  CHECK_UTR_HISTORY: [
    'id',
    'sno',
    'payin_id',
    'utr',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
    'company_id',
    'is_obsolete',
    'config',
  ],
  RESET_DATA_HISTORY: [
    'id',
    'sno',
    'payin_id',
    'pre_status',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
    'config',
  ],
  BANK_RESPONSE: [
    'id',
    'sno',
    'status',
    'bank_id',
    'amount',
    'upi_short_code',
    'utr',
    'is_used',
    'created_at',
    'updated_at',
    'created_by',
    'config',
    'updated_by',
  ],
};
export const merchantColumns = {
  MERCHANT: [
    'first_name',
    'last_name',
    'user_id',
    'code',
    'min_payin',
    'max_payin',
    'payin_commission',
    'min_payout',
    'max_payout',
    'payout_commission',
    'balance',
    'config',
    'subMerchants',
  ],
  USER: [
    'id', // -- while enabling user id going undefined
    'first_name',
    'last_name',
    'email',
    'contact_no',
    'user_name',
    'is_enabled',
    'code',
  ],
  SETTLEMENT: [
    'id',
    'sno',
    'status',
    'amount',
    'method',
    'config',
    'user_id',
    'created_at',
    'updated_at',
    'approved_at',
    'rejected_at',
  ],
  CALCULATION: [
    'total_payin_count',
    'total_payin_amount',
    'total_payin_commission',
    'total_payout_count',
    'total_payout_amount',
    'total_payout_commission',
    'total_settlement_count',
    'total_settlement_amount',
    'total_chargeback_count',
    'total_chargeback_amount',
    'current_balance',
    'net_balance',
    'total_reverse_payout_count',
    'total_reverse_payout_amount',
    'total_reverse_payout_commission',
  ],
  COMPLAINTS: ['sno', 'status', 'email', 'config'],
  PAYIN: [
    'id',
    'sno',
    'qr_params',
    'amount',
    'status',
    'is_notified',
    'user_submitted_utr',
    'currency',
    'merchant_order_id',
    'user',
    'payin_merchant_commission',
    'user_submitted_image',
    'duration',
    'config',
  ],
  PAYOUT: [
    'id',
    'sno',
    'user',
    'amount',
    'status',
    'failed_reason',
    'currency',
    'merchant_order_id',
    'acc_no',
    'acc_holder_name',
    'ifsc_code',
    'bank_name',
    'upi_id',
    'utr_id',
    'rejected_reason',
    'payout_merchant_commission',
    'config',
  ],
  CHARGE_BACK: ['sno', 'merchant_user_id', 'amount', 'reference_date'],
  USER_HIERARCHY: ['config'],
  BANK_ACCOUNT: [
    'upi_id',
    'upi_params',
    'nick_name',
    'acc_no',
    'acc_name',
    'bank_name',
    'is_qr',
    'is_bank',
    'is_enabled',
    'config',
  ],
  BANK_RESPONSE: [
    'id',
    'sno',
    'status',
    'bank_id',
    'amount',
    'upi_short_code',
    'utr',
    'is_used',
    'config',
  ],
};
export const vendorColumns = {
  USER: [
    'first_name',
    'last_name',
    'email',
    'contact_no',
    'user_name',
    'code',
    'created_at', //-- need bank details within date range
  ],
  SETTLEMENT: [
    'id',
    'sno',
    'status',
    'amount',
    'method',
    'config',
    'user_id',
    'created_at',
    'updated_at',
    'approved_at',
    'rejected_at',
  ],
  CALCULATION: [
    'total_payin_count',
    'total_payin_amount',
    'total_payin_commission',
    'total_payout_count',
    'total_payout_amount',
    'total_payout_commission',
    'total_settlement_count',
    'total_settlement_amount',
    'total_chargeback_count',
    'total_chargeback_amount',
    'current_balance',
    'net_balance',
    'total_reverse_payout_count',
    'total_reverse_payout_amount',
    'total_reverse_payout_commission',
  ],
  COMPLAINTS: ['sno', 'status', 'email', 'config'],
  PAYIN: [
    'id',
    'sno',
    'qr_params',
    'amount',
    'status',
    'user_submitted_utr',
    'currency',
    'user',
    'payin_vendor_commission',
    'user_submitted_image',
    'duration',
    'config',
  ],
  PAYOUT: [
    'id',
    'sno',
    'user',
    'amount',
    'status',
    'failed_reason',
    'currency',
    'acc_no',
    'acc_holder_name',
    'ifsc_code',
    'bank_name',
    'upi_id',
    'utr_id',
    'rejected_reason',
    'payout_vendor_commission',
    'config',
  ],
  BANK_ACCOUNT: [
    'id',
    'sno',
    'upi_id',
    'upi_params',
    'nick_name',
    'acc_no',
    'acc_name',
    'ifsc_code',
    'bank_name',
    'is_qr',
    'is_bank',
    'is_enabled',
    'payin_count',
    'balance',
    'today_balance',
    'bank_used_for',
    'config',
  ],
  BANK_RESPONSE: ['id', 'sno', 'status', 'bank_id', 'amount', 'utr', 'is_used'],
  VENDOR: [
    'first_name',
    'last_name',
    'code',
    'payin_commission',
    'payout_commission',
    'balance',
    'config',
    'subVendors',
  ],
  CHARGE_BACK: [
    'sno',
    'vendor_user_id',
    'bank_acc_id',
    'amount',
    'reference_date',
    'created_at',
  ],
};
export const tableName = {
  USER: 'User',
  MERCHANT: 'Merchant',
  ROLE: 'Role',
  COMPANY: 'Company',
  CALCULATION: 'Calculation',
  COMPLAINTS: 'Complaints',
  DESIGNATION: 'Designation',
  PAYIN: 'Payin',
  PAYOUT: 'Payout',
  VENDOR: 'Vendor',
  CHARGE_BACK: 'ChargeBack',
  BANK_ACCOUNT: 'BankAccount',
  USER_HIERARCHY: 'UserHierarchy',
  SETTLEMENT: 'Settlement',
  CHECK_UTR_HISTORY: 'CheckUtrHistory',
  RESET_DATA_HISTORY: 'ResetDataHistory',
  BANK_RESPONSE: 'BankResponse',
  ACCESS_TOKEN: 'AccessToken',
  USER_OTP: 'UserOtp',
  BENEFICIARY_ACCOUNTS: 'BeneficiaryAccounts',
  NOTIFICATIONS: 'Notifications',
  NOTIFICATION_RECIPIENTS: 'NotificationRecipients',
  BANK_HISTORY: 'BankHistory',
};

export const BankTypes = {
  UPI: 'upi',
  PHONE_PE: 'phone_pe',
  BANK_TRANSFER: 'bank_transfer',
  INTENT: 'intent',
};

export const AccessRoles = {
  ALL: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.OPERATIONS,
    Role.MERCHANT,
    Role.MERCHANT_OPERATIONS,
    Role.SUB_MERCHANT,
    Role.VENDOR,
    Role.VENDOR_ADMIN,
    Role.SUB_VENDOR,
    Role.VENDOR_OPERATIONS,
  ],
  USER: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.OPERATIONS,
    Role.SUB_MERCHANT,
    Role.MERCHANT,
    Role.VENDOR,
    Role.VENDOR_ADMIN,
    Role.SUB_VENDOR,
  ],
  MERCHANT: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.OPERATIONS,
    Role.MERCHANT,
    Role.SUB_MERCHANT,
    Role.MERCHANT_OPERATIONS,
  ],
  VENDOR: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.OPERATIONS,
    Role.VENDOR,
    Role.SUB_VENDOR,
    Role.VENDOR_ADMIN,
    Role.VENDOR_OPERATIONS,
  ],
  PAYIN: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.OPERATIONS,
    Role.MERCHANT,
    Role.SUB_MERCHANT,
    Role.MERCHANT_OPERATIONS,
    Role.VENDOR,
    Role.SUB_VENDOR,
    Role.VENDOR_ADMIN,
    Role.VENDOR_OPERATIONS,
  ],
  PAYOUT: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.OPERATIONS,
    Role.MERCHANT,
    Role.SUB_MERCHANT,
    Role.MERCHANT_OPERATIONS,
    Role.VENDOR,
    Role.VENDOR_ADMIN,
    Role.SUB_VENDOR,
    Role.VENDOR_OPERATIONS,
  ],
  SETTLEMENT: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.OPERATIONS,
    Role.MERCHANT,
    Role.SUB_MERCHANT,
    Role.MERCHANT_OPERATIONS,
    Role.VENDOR,
    Role.VENDOR_ADMIN,
    Role.SUB_VENDOR,
    Role.VENDOR_OPERATIONS,
  ],
  REPORT: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.OPERATIONS,
    Role.MERCHANT,
    Role.SUB_MERCHANT,
    Role.MERCHANT_OPERATIONS,
    Role.VENDOR,
    Role.SUB_VENDOR,
    Role.VENDOR_ADMIN,
    Role.VENDOR_OPERATIONS,
  ],
  COMPANY: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.OPERATIONS,
    Role.VENDOR,
    Role.SUB_VENDOR,
    Role.VENDOR_ADMIN,
    Role.VENDOR_OPERATIONS,
  ],
  USER_HIERARCHY: {
    CREATE_DELETE: [Role.ADMIN, Role.TRANSACTIONS],
    UPDATE_READ: [Role.ADMIN, Role.TRANSACTIONS, Role.MERCHANT],
  },
  RESET_DATA_HISTORY: [Role.ADMIN, Role.OPERATIONS, Role.TRANSACTIONS],
  CHECK_UTR_HISTORY: [Role.ADMIN, Role.OPERATIONS, Role.TRANSACTIONS],
  BANK_RESPONSE: [
    Role.ADMIN,
    Role.OPERATIONS,
    Role.TRANSACTIONS,
    Role.VENDOR,
    Role.SUB_VENDOR,
    Role.VENDOR_ADMIN,
    Role.VENDOR_OPERATIONS,
  ],
  BANK_ACCOUNT: [
    Role.ADMIN,
    Role.OPERATIONS,
    Role.TRANSACTIONS,
    Role.VENDOR,
    Role.SUB_VENDOR,
    Role.VENDOR_ADMIN,
    Role.VENDOR_OPERATIONS,
  ],
  CHARGE_BACK: {
    GET: [
      Role.ADMIN,
      Role.TRANSACTIONS,
      Role.MERCHANT_ADMIN,
      Role.MERCHANT,
      Role.VENDOR,
      Role.VENDOR_ADMIN,
      Role.SUB_VENDOR,
    ],
    CREATE_DELETE: [Role.ADMIN, Role.TRANSACTIONS, Role.MERCHANT],
    UPDATE_READ: [
      Role.ADMIN,
      Role.TRANSACTIONS,
      Role.MERCHANT_ADMIN,
      Role.MERCHANT,
      Role.VENDOR,
      Role.VENDOR_ADMIN,
      Role.SUB_VENDOR,
    ],
  },
  CALCULATION: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.OPERATIONS,
    Role.MERCHANT,
    Role.VENDOR,
    Role.VENDOR_ADMIN,
    Role.MERCHANT_OPERATIONS,
    Role.VENDOR_OPERATIONS,
    Role.SUB_MERCHANT,
    Role.SUB_VENDOR,
  ],
  ROLES: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.SUB_MERCHANT,
    Role.MERCHANT,
    Role.VENDOR,
    Role.VENDOR_ADMIN,
    Role.SUB_VENDOR,
  ],
  DESIGNATION: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.SUB_MERCHANT,
    Role.MERCHANT,
    Role.VENDOR,
    Role.VENDOR_ADMIN,
    Role.SUB_VENDOR,
  ],
  COMPLAINTS: [Role.ADMIN],
  BENEFICIARY_ACCOUNTS: [
    Role.ADMIN,
    Role.TRANSACTIONS,
    Role.OPERATIONS,
    Role.MERCHANT,
    Role.VENDOR,
    Role.VENDOR_ADMIN,
    Role.SUB_VENDOR,
    Role.VENDOR_OPERATIONS,
  ],
};
export const COUNTRIES = [
  'India',
  'United Arab Emirates',
  'Pakistan',
  'Brazil',
]; ///add brazil for temp

export const europeanCountries = [
  'Albania',
  'Andorra',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Belarus',
  'Belgium',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Georgia',
  'Germany',
  'Greece',
  'Hungary',
  'Iceland',
  'Ireland',
  'Italy',
  'Kazakhstan',
  'Kosovo',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Moldova',
  'Monaco',
  'Montenegro',
  'Netherlands',
  'North Macedonia',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'San Marino',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Turkey',
  'Ukraine',
  'United Kingdom',
  'Vatican City',
];

export const payAssistErrorCodeMap = {
  11: 'Insufficient Funds',
  12: 'Transaction already exists',
  13: 'Insufficient Funds',
  14: 'Invalid Account Details',
  15: 'Invalid Account Details',
  TXF: 'Transaction Failed',
  ERR: 'Server Unreachable',
};

export const unblocked_countries = [
  {
    country: 'India',
    regions: [
      'Andaman and Nicobar Islands',
      'Andhra Pradesh',
      'Arunachal Pradesh',
      'Assam',
      'Bihar',
      'Chandigarh',
      'Chhattisgarh',
      'Dadra and Nagar Haveli and Daman and Diu',
      'Delhi',
      'Goa',
      'Himachal Pradesh',
      'Jammu and Kashmir',
      'Jharkhand',
      'Karnataka',
      'Kerala',
      'Ladakh',
      'Lakshadweep',
      'Madhya Pradesh',
      'Maharashtra',
      'Manipur',
      'Meghalaya',
      'Mizoram',
      'Nagaland',
      'Odisha',
      'Puducherry',
      'Punjab',
      'Rajasthan',
      'Sikkim',
      'Tamil Nadu',
      'Telangana',
      'Tripura',
      'Uttar Pradesh',
      'Uttarakhand',
      'West Bengal',
    ],
  },
  { country: 'United Arab Emirates', regions: [] },
  { country: 'Pakistan', regions: [] },
];

export const userFields = [
  'full_name^2', // Boost full_name
  'contact_no',
  'user_name',
  'code',
  'designation',
  'email',
];
export const bankResponseSearchableFields = [
  'id',
  'sno',
  'status',
  'bank_id',
  'amount',
  'upi_short_code',
  'utr',
  'created_by',
  'config',
  'updated_by',
  'nick_name',
];

export const payinSearchableFields = [
  'id',
  'sno',
  'upi_short_code',
  'amount',
  'status',
  'user_submitted_utr',
  'merchant_order_id',
  'user',
  'bank_acc_id',
  'merchant_id',
  'bank_response_id',
  'payin_merchant_commission',
  'payin_vendor_commission',
  'company_id',
  'created_by',
  'updated_by',
  'nick_name',
  'vendor_code',
  "merchant_details.merchant_code"
];

export const PayoutSearchableFields = [
  'id',
  'sno',
  'user',
  'merchant_id',
  'bank_acc_id',
  'amount',
  'status',
  'failed_reason',
  'currency',
  'merchant_order_id',
  'acc_no',
  'acc_holder_name',
  'ifsc_code',
  'bank_name',
  'upi_id',
  'utr_id',
  'rejected_reason',
  'payout_merchant_commission',
  'payout_vendor_commission',
  'config',
  'created_by',
  'updated_by',
  'vendor_code',
  'nick_name',
  'payout_details.method',
  "merchant_details.merchant_code",
  "user_bank_details.account_no",
  "user_bank_details.ifsc_code",
  "user_bank_details.bank_name",
  "user_bank_details.account_holder_name",
];
export const SettlementSearchableFields = [
  'id',
  'sno',
  'status',
  'amount',
  'method',
  'config',
  'user_id',
  'created_by',
  'updated_by',
  'code',
  'config.ifsc',
  'config.acc_no',
  'config.acc_holder_name',
  'config.bank_name',
  'config.debit_credit',
  'config.reference_id',
  'config.description',
];

export const PayinResponses = {
  VENDOR: [
    'id',
    'sno',
    'amount',
    'status',
    'user_submitted_utr',
    'user_submitted_image',
    'duration',
    'nick_name',
    'bank_acc_id',
    'bank_res_details',
    'created_at',
    'updated_at',
    'payin_vendor_commission',
    'vendor_code',
  ],
  MERCHANT: [
    'id',
    'sno',
    'amount',
    'status',
    'user_submitted_utr',
    'user_submitted_image',
    'duration',
    'nick_name',
    'bank_acc_id',
    'bank_res_details',
    'config',
    'created_at',
    'updated_at',
    'payin_merchant_commission',
    'merchant_order_id',
    'user',
    'is_notified',
    'payin_details',
    'merchant_details',
  ],
  ADMIN: [
    'id',
    'sno',
    'amount',
    'status',
    'user_submitted_utr',
    'user_submitted_image',
    'duration',
    'nick_name',
    'bank_acc_id',
    'bank_res_details',
    'created_at',
    'updated_at',
    'config',
    'payin_merchant_commission',
    'merchant_details',
    'merchant_order_id',
    'payin_details',
    'payin_vendor_commission',
    'vendor_code',
    'vendor_user_id',
    'upi_short_code',
    'is_url_expires',
    'approved_at',
    'created_by',
    'updated_by',
    'is_notified',
    'user',
  ],
};

export const PayoutResponses = {
  VENDOR: [
    'id',
    'sno',
    'amount',
    'status',
    'failed_reason',
    'currency',
    'upi_id',
    'utr_id',
    'rejected_reason',
    'payout_vendor_commission',
    'vendor_code',
    'payout_method',
    'nick_name',
    'user_bank_details',
    'created_at',
    'updated_at',
    'approved_at',
    'rejected_at',
  ],
  MERCHANT: [
    'id',
    'sno',
    'amount',
    'status',
    'failed_reason',
    'currency',
    'upi_id',
    'utr_id',
    'rejected_reason',
    'payout_merchant_commission',
    'merchant_order_id',
    'user',
    'merchant_details',
    'nick_name',
    'user_bank_details',
    'created_at',
    'updated_at',
    'approved_at',
    'rejected_at',
  ],
  ADMIN: [
    'id',
    'sno',
    'amount',
    'status',
    'failed_reason',
    'currency',
    'upi_id',
    'utr_id',
    'rejected_reason',
    'merchant_id',
    'payout_merchant_commission',
    'payout_vendor_commission',
    'merchant_order_id',
    'bank_acc_id',
    'approved_at',
    'created_by',
    'updated_by',
    'user',
    'created_at',
    'vendor_code',
    'vendor_id',
    'vendor_user_id',
    'payout_details',
    'updated_at',
    'user_id',
    'merchant_details', 
    'nick_name',
    'user_bank_details',
  ]
};

export const BankResponseKeys = {
  VENDOR: [
    'id',
    'sno',
    'amount',
    'status',
    'utr',
    'is_used',
    'upi_short_code',
    'vendor_code',
    'nick_name',
    'created_at',
    'updated_at',
  ],
  ADMIN: [
    'id',
    'sno',
    'amount',
    'status',
    'utr',
    'is_used',
    'upi_short_code',
    'bank_id',
    'company_id',
    'created_by',
    'updated_by',
    'vendor_code',
    'vendor_user_id',
    'nick_name',
    'created_at',
    'updated_at',
  ],
};

export const SettlementResponses = {
  ADMIN: [
    'id',
    'sno',
    'user_id',
    'status',
    'amount',
    'method',
    'config',
    'approved_at',
    'rejected_at',
    'created_by',
    'updated_by',
    'created_at',
    'updated_at',
    'code',
  ],
  MERCHANT: [
    'id',
    'sno',
    'user_id',
    'status',
    'amount',
    'method',
    'config',
    'approved_at',
    'rejected_at',
    'created_at',
    'updated_at',
    'code',
  ],
  VENDOR: [
    'id',
    'sno',
    'user_id',
    'status',
    'amount',
    'method',
    'config',
    'approved_at',
    'rejected_at',
    'created_at',
    'updated_at',
    'code',
  ],
};