
-- PostgreSQL database dump

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


--
-- Name: set_updated_at_column(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.set_updated_at_column() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AccessToken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AccessToken" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    is_obsolete boolean DEFAULT false,
    config json DEFAULT '{}'::json NOT NULL,
    session_id character varying NOT NULL
);


--
-- Name: BankAccount; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BankAccount" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    sno integer NOT NULL,
    user_id character varying NOT NULL,
    upi_id character varying NOT NULL,
    upi_params character varying,
    nick_name character varying NOT NULL,
    acc_holder_name character varying NOT NULL,
    acc_no character varying NOT NULL,
    ifsc character varying NOT NULL,
    bank_name character varying NOT NULL,
    is_qr boolean DEFAULT false,
    is_bank boolean DEFAULT false,
    min double precision NOT NULL,
    max double precision NOT NULL,
    is_enabled boolean DEFAULT false,
    payin_count integer NOT NULL,
    balance double precision DEFAULT 0 NOT NULL,
    today_balance double precision DEFAULT 0 NOT NULL,
    bank_used_for character varying DEFAULT ''::character varying,
    config json DEFAULT '{}'::json NOT NULL,
    created_by character varying,
    updated_by character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    is_obsolete boolean DEFAULT false
);


--
-- Name: COLUMN "BankAccount".config; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."BankAccount".config IS '"merchant" : [merchant1, merchant2]';


--
-- Name: BankAccount_sno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."BankAccount" ALTER COLUMN sno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BankAccount_sno_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: BankHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BankHistory" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    bank_account_id character varying NOT NULL,
    today_balance double precision DEFAULT 0 NOT NULL,
    today_current_balance double precision DEFAULT 0 NOT NULL,
    config json DEFAULT '{}'::json NOT NULL,
    is_obsolete boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    count integer DEFAULT 0 NOT NULL
);


--
-- Name: BankResponse; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BankResponse" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    sno integer NOT NULL,
    status character varying NOT NULL,
    bank_id character varying NOT NULL,
    amount double precision NOT NULL,
    upi_short_code character varying,
    utr character varying,
    is_used boolean NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    created_by character varying,
    updated_by character varying,
    company_id character varying NOT NULL,
    is_obsolete boolean DEFAULT false,
    config json DEFAULT '{}'::json NOT NULL
);


--
-- Name: BankResponse_sno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."BankResponse" ALTER COLUMN sno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BankResponse_sno_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: BeneficiaryAccounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BeneficiaryAccounts" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id character varying NOT NULL,
    bank_name character varying NOT NULL,
    acc_holder_name character varying(255) NOT NULL,
    acc_no character varying NOT NULL,
    ifsc character varying NOT NULL,
    upi_id character varying DEFAULT ''::character varying,
    created_at timestamp with time zone DEFAULT now(),
    config json DEFAULT '{}'::json NOT NULL,
    updated_at timestamp with time zone DEFAULT now(),
    created_by character varying,
    updated_by character varying,
    is_obsolete boolean DEFAULT false NOT NULL,
    role_id character varying,
    company_id character varying NOT NULL
);


--
-- Name: Calculation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Calculation" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id character varying NOT NULL,
    role_id character varying NOT NULL,
    total_payin_count integer DEFAULT 0,
    total_payin_amount double precision DEFAULT 0,
    total_payin_commission double precision DEFAULT 0,
    total_payout_count integer DEFAULT 0,
    total_payout_amount double precision DEFAULT 0,
    total_payout_commission double precision DEFAULT 0,
    total_settlement_count integer DEFAULT 0,
    total_settlement_amount double precision DEFAULT 0,
    total_chargeback_count integer DEFAULT 0,
    total_chargeback_amount double precision DEFAULT 0,
    total_reverse_payout_count integer DEFAULT 0,
    total_reverse_payout_amount double precision DEFAULT 0,
    total_reverse_payout_commission double precision DEFAULT 0,
    current_balance double precision DEFAULT 0,
    net_balance double precision DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    is_obsolete boolean DEFAULT false,
    config json DEFAULT '{}'::json NOT NULL,
    created_by character varying,
    updated_by character varying,
    total_settlement_commission double precision DEFAULT 0,
    total_adjustment_amount double precision DEFAULT 0,
    total_adjustment_commission double precision DEFAULT 0,
    total_adjustment_count integer DEFAULT 0
);


--
-- Name: ChargeBack; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ChargeBack" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    sno integer NOT NULL,
    "user" character varying,
    merchant_user_id character varying NOT NULL,
    vendor_user_id character varying NOT NULL,
    payin_id character varying NOT NULL,
    bank_acc_id character varying NOT NULL,
    amount double precision NOT NULL,
    reference_date timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    is_obsolete boolean DEFAULT false,
    config json DEFAULT '{}'::json NOT NULL,
    created_by character varying,
    updated_by character varying
);


--
-- Name: ChargeBack_sno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ChargeBack" ALTER COLUMN sno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ChargeBack_sno_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: CheckUtrHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."CheckUtrHistory" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    sno integer NOT NULL,
    payin_id character varying NOT NULL,
    utr character varying NOT NULL,
    created_by character varying,
    updated_by character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    is_obsolete boolean DEFAULT false,
    config json DEFAULT '{}'::json NOT NULL
);


--
-- Name: CheckUtrHistory_sno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."CheckUtrHistory" ALTER COLUMN sno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CheckUtrHistory_sno_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Company; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Company" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    email character varying NOT NULL,
    contact_no character varying NOT NULL,
    config json DEFAULT '{}'::json NOT NULL,
    is_obsolete boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: Complaints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Complaints" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    sno integer NOT NULL,
    status character varying NOT NULL,
    payin_id character varying NOT NULL,
    email character varying NOT NULL,
    config json DEFAULT '{}'::json NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    created_by character varying,
    updated_by character varying
);


--
-- Name: COLUMN "Complaints".config; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."Complaints".config IS 'title, complaint';


--
-- Name: Complaints_sno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Complaints" ALTER COLUMN sno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Complaints_sno_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Designation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Designation" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    designation character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    is_obsolete boolean DEFAULT false,
    role_id character varying NOT NULL
);


--
-- Name: Merchant; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Merchant" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id character varying NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    code character varying NOT NULL,
    min_payin double precision NOT NULL,
    max_payin double precision NOT NULL,
    payin_commission double precision NOT NULL,
    min_payout double precision NOT NULL,
    max_payout double precision NOT NULL,
    payout_commission double precision NOT NULL,
    is_test_mode boolean DEFAULT false,
    is_enabled boolean DEFAULT true,
    dispute_enabled boolean DEFAULT true,
    is_demo boolean DEFAULT false,
    balance double precision NOT NULL,
    company_id character varying NOT NULL,
    config json DEFAULT '{}'::json NOT NULL,
    created_by character varying,
    updated_by character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    is_obsolete boolean DEFAULT false
);


--
-- Name: COLUMN "Merchant".config; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."Merchant".config IS 'site_url, notify_url, return_url, payout_notify_url, api_key, secret_key, public_api_key, banks, "beneficiary": [{bankname, ifsc, account_name_holder, method}]';


--
-- Name: NotificationRecipients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."NotificationRecipients" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    notification_id character varying NOT NULL,
    company_id character varying NOT NULL,
    config jsonb DEFAULT '{}'::jsonb,
    is_obsolete boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: Notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Notifications" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    message character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    user_id character varying NOT NULL,
    config jsonb DEFAULT '{}'::jsonb,
    is_obsolete boolean DEFAULT false
);


--
-- Name: Payin; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Payin" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    sno integer NOT NULL,
    upi_short_code character varying NOT NULL,
    qr_params character varying,
    amount double precision NOT NULL,
    status character varying NOT NULL,
    is_notified boolean DEFAULT false NOT NULL,
    user_submitted_utr character varying,
    currency character varying NOT NULL,
    merchant_order_id character varying NOT NULL,
    "user" character varying NOT NULL,
    bank_acc_id character varying,
    merchant_id character varying NOT NULL,
    bank_response_id character varying,
    payin_merchant_commission double precision,
    payin_vendor_commission double precision,
    user_submitted_image character varying,
    duration character varying,
    is_url_expires boolean DEFAULT false,
    expiration_date timestamp with time zone NOT NULL,
    one_time_used boolean DEFAULT false,
    approved_at timestamp with time zone,
    failed_at timestamp with time zone,
    config json DEFAULT '{}'::json NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying,
    is_obsolete boolean DEFAULT false NOT NULL,
    created_by character varying,
    updated_by character varying
);


--
-- Name: COLUMN "Payin".config; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."Payin".config IS 'notify_url';


--
-- Name: Payin_sno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Payin" ALTER COLUMN sno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Payin_sno_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Payout; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Payout" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    sno integer NOT NULL,
    "user" character varying NOT NULL,
    merchant_id character varying NOT NULL,
    vendor_id character varying,
    bank_acc_id character varying,
    amount double precision NOT NULL,
    status character varying DEFAULT 'INITIATED'::character varying NOT NULL,
    failed_reason character varying,
    currency character varying DEFAULT 'INR'::character varying NOT NULL,
    merchant_order_id character varying NOT NULL,
    acc_no character varying NOT NULL,
    acc_holder_name character varying NOT NULL,
    ifsc_code character varying NOT NULL,
    bank_name character varying,
    upi_id character varying,
    utr_id character varying,
    rejected_reason character varying,
    payout_merchant_commission double precision DEFAULT 0 NOT NULL,
    payout_vendor_commission double precision DEFAULT 0 NOT NULL,
    approved_at timestamp with time zone,
    rejected_at timestamp with time zone,
    config json DEFAULT '{}'::json NOT NULL,
    created_by character varying,
    updated_by character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    is_obsolete boolean DEFAULT false
);


--
-- Name: COLUMN "Payout".config; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."Payout".config IS 'notify_url';


--
-- Name: Payout_sno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Payout" ALTER COLUMN sno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Payout_sno_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ResetDataHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ResetDataHistory" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    sno integer NOT NULL,
    payin_id character varying NOT NULL,
    pre_status character varying,
    created_by character varying,
    updated_by character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    is_obsolete boolean DEFAULT false,
    config json DEFAULT '{}'::json NOT NULL
);


--
-- Name: ResetDataHistory_sno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ResetDataHistory" ALTER COLUMN sno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ResetDataHistory_sno_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Role; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Role" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    role character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    is_obsolete boolean DEFAULT false
);


--
-- Name: Settlement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Settlement" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    sno integer NOT NULL,
    user_id character varying NOT NULL,
    status character varying NOT NULL,
    amount double precision NOT NULL,
    method character varying NOT NULL,
    config json DEFAULT '{}'::json NOT NULL,
    approved_at timestamp with time zone,
    rejected_at timestamp with time zone,
    created_by character varying,
    updated_by character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    is_obsolete boolean DEFAULT false
);


--
-- Name: COLUMN "Settlement".config; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."Settlement".config IS 'acc_name, acc_no, ifsc, reference_id, rejected_reason, wallet, wallet_address, wallet_balance';


--
-- Name: Settlement_sno_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Settlement" ALTER COLUMN sno ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Settlement_sno_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: SystemSettings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."SystemSettings" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    key character varying NOT NULL,
    value json DEFAULT '{}'::json NOT NULL,
    config json DEFAULT '{}'::json NOT NULL,
    created_by character varying,
    updated_by character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    is_obsolete boolean DEFAULT false
);


--
-- Name: TABLE "SystemSettings"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public."SystemSettings" IS 'System-wide configuration settings';


--
-- Name: COLUMN "SystemSettings".key; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."SystemSettings".key IS 'Unique setting key identifier';


--
-- Name: COLUMN "SystemSettings".value; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."SystemSettings".value IS 'Setting value stored as JSON';


--
-- Name: COLUMN "SystemSettings".config; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."SystemSettings".config IS 'Additional metadata for the setting';


--
-- Name: User; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."User" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    role_id character varying NOT NULL,
    company_id character varying NOT NULL,
    designation_id character varying NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    email character varying NOT NULL,
    contact_no character varying NOT NULL,
    user_name character varying NOT NULL,
    password character varying NOT NULL,
    code character varying,
    is_enabled boolean DEFAULT true,
    last_login timestamp with time zone,
    last_logout timestamp with time zone,
    config json DEFAULT '{}'::json NOT NULL,
    created_by character varying,
    updated_by character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    is_obsolete boolean DEFAULT false,
    is_two_factor_enabled boolean DEFAULT false NOT NULL,
    two_factor_secret text,
    -- is_two_factor_required boolean DEFAULT false NOT NULL,
    is_two_factor_exempt boolean DEFAULT false NOT NULL
);


--
-- Name: COLUMN "User".is_two_factor_enabled; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."User".is_two_factor_enabled IS 'User-set flag: whether user has completed 2FA setup (scanned QR + verified OTP)';


--
-- Name: COLUMN "User".is_two_factor_required; Type: COMMENT; Schema: public; Owner: -
--

-- COMMENT ON COLUMN public."User".is_two_factor_required IS 'Admin-set flag: whether 2FA is mandatory for this user';


--
-- Name: COLUMN "User".is_two_factor_exempt; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."User".is_two_factor_exempt IS 'Admin-set flag: whether user is exempt from global 2FA enforcement';


--
-- Name: UserHierarchy; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."UserHierarchy" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id character varying NOT NULL,
    config json DEFAULT '{}'::json NOT NULL,
    created_by character varying,
    updated_by character varying,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    is_obsolete boolean DEFAULT false
);


--
-- Name: COLUMN "UserHierarchy".config; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."UserHierarchy".config IS '"merchant_admin_user_id || vendor_admin_user_id" : [merchant1user, merchant2user || vendor1user, vendor2user]';


--
-- Name: UserOtp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."UserOtp" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id character varying NOT NULL,
    otp integer NOT NULL,
    expiration_time timestamp with time zone NOT NULL,
    is_used boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: Vendor; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Vendor" (
    id character varying DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id character varying NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    code character varying NOT NULL,
    payin_commission double precision NOT NULL,
    payout_commission double precision NOT NULL,
    balance double precision NOT NULL,
    created_by character varying,
    updated_by character varying,
    config json DEFAULT '{}'::json NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    company_id character varying NOT NULL,
    is_obsolete boolean DEFAULT false
);


--
-- Name: COLUMN "Vendor".config; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public."Vendor".config IS '"beneficiary": [{bankname, ifsc, account_name_holder, method}]';


--
-- Name: user_for_es; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.user_for_es AS
 SELECT u.id,
    u.role_id,
    u.designation_id,
    u.first_name,
    u.last_name,
    (((u.first_name)::text || ' '::text) || (u.last_name)::text) AS full_name,
    u.email,
    u.contact_no,
    u.user_name,
    u.code,
    u.is_enabled,
    u.last_login,
    u.last_logout,
    u.config,
    d.designation,
    cu.user_name AS created_by,
    uu.user_name AS updated_by,
    u.created_at,
    u.updated_at
   FROM (((public."User" u
     LEFT JOIN public."Designation" d ON (((u.designation_id)::text = (d.id)::text)))
     LEFT JOIN public."User" cu ON (((u.created_by)::text = (cu.id)::text)))
     LEFT JOIN public."User" uu ON (((u.updated_by)::text = (uu.id)::text)))
  WHERE (u.is_obsolete = false);


--
-- Name: AccessToken AccessToken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AccessToken"
    ADD CONSTRAINT "AccessToken_pkey" PRIMARY KEY (id);


--
-- Name: BankAccount BankAccount_nick_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BankAccount"
    ADD CONSTRAINT "BankAccount_nick_name_key" UNIQUE (nick_name);


--
-- Name: BankAccount BankAccount_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BankAccount"
    ADD CONSTRAINT "BankAccount_pkey" PRIMARY KEY (id);


--
-- Name: BankHistory BankHistory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BankHistory"
    ADD CONSTRAINT "BankHistory_pkey" PRIMARY KEY (id);


--
-- Name: BankResponse BankResponse_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BankResponse"
    ADD CONSTRAINT "BankResponse_pkey" PRIMARY KEY (id);


--
-- Name: BeneficiaryAccounts BeneficiaryAccounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BeneficiaryAccounts"
    ADD CONSTRAINT "BeneficiaryAccounts_pkey" PRIMARY KEY (id);


--
-- Name: Calculation Calculation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Calculation"
    ADD CONSTRAINT "Calculation_pkey" PRIMARY KEY (id);


--
-- Name: ChargeBack ChargeBack_payin_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ChargeBack"
    ADD CONSTRAINT "ChargeBack_payin_id_key" UNIQUE (payin_id);


--
-- Name: ChargeBack ChargeBack_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ChargeBack"
    ADD CONSTRAINT "ChargeBack_pkey" PRIMARY KEY (id);


--
-- Name: CheckUtrHistory CheckUtrHistory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."CheckUtrHistory"
    ADD CONSTRAINT "CheckUtrHistory_pkey" PRIMARY KEY (id);


--
-- Name: Company Company_contact_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Company"
    ADD CONSTRAINT "Company_contact_no_key" UNIQUE (contact_no);


--
-- Name: Company Company_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Company"
    ADD CONSTRAINT "Company_email_key" UNIQUE (email);


--
-- Name: Company Company_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Company"
    ADD CONSTRAINT "Company_pkey" PRIMARY KEY (id);


--
-- Name: Complaints Complaints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Complaints"
    ADD CONSTRAINT "Complaints_pkey" PRIMARY KEY (id);


--
-- Name: Designation Designation_designation_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Designation"
    ADD CONSTRAINT "Designation_designation_key" UNIQUE (designation);


--
-- Name: Designation Designation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Designation"
    ADD CONSTRAINT "Designation_pkey" PRIMARY KEY (id);


--
-- Name: Merchant Merchant_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Merchant"
    ADD CONSTRAINT "Merchant_code_key" UNIQUE (code);


--
-- Name: Merchant Merchant_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Merchant"
    ADD CONSTRAINT "Merchant_pkey" PRIMARY KEY (id);


--
-- Name: Merchant Merchant_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Merchant"
    ADD CONSTRAINT "Merchant_user_id_key" UNIQUE (user_id);


--
-- Name: NotificationRecipients NotificationRecipients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."NotificationRecipients"
    ADD CONSTRAINT "NotificationRecipients_pkey" PRIMARY KEY (id);


--
-- Name: Notifications Notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT "Notifications_pkey" PRIMARY KEY (id);


--
-- Name: Payin Payin_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Payin"
    ADD CONSTRAINT "Payin_pkey" PRIMARY KEY (id);


--
-- Name: Payout Payout_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Payout"
    ADD CONSTRAINT "Payout_pkey" PRIMARY KEY (id);


--
-- Name: ResetDataHistory ResetDataHistory_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ResetDataHistory"
    ADD CONSTRAINT "ResetDataHistory_pkey" PRIMARY KEY (id);


--
-- Name: Role Role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Role"
    ADD CONSTRAINT "Role_pkey" PRIMARY KEY (id);


--
-- Name: Settlement Settlement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Settlement"
    ADD CONSTRAINT "Settlement_pkey" PRIMARY KEY (id);


--
-- Name: SystemSettings SystemSettings_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SystemSettings"
    ADD CONSTRAINT "SystemSettings_key_key" UNIQUE (key);


--
-- Name: SystemSettings SystemSettings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."SystemSettings"
    ADD CONSTRAINT "SystemSettings_pkey" PRIMARY KEY (id);


--
-- Name: UserHierarchy UserHierarchy_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserHierarchy"
    ADD CONSTRAINT "UserHierarchy_pkey" PRIMARY KEY (id);


--
-- Name: UserHierarchy UserHierarchy_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserHierarchy"
    ADD CONSTRAINT "UserHierarchy_user_id_key" UNIQUE (user_id);


--
-- Name: UserOtp UserOtp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserOtp"
    ADD CONSTRAINT "UserOtp_pkey" PRIMARY KEY (id);


--
-- Name: User User_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_code_key" UNIQUE (code);


--
-- Name: User User_contact_no_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_contact_no_key" UNIQUE (contact_no);


--
-- Name: User User_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY (id);


--
-- Name: User User_user_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_user_name_key" UNIQUE (user_name);


--
-- Name: Vendor Vendor_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Vendor"
    ADD CONSTRAINT "Vendor_code_key" UNIQUE (code);


--
-- Name: Vendor Vendor_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Vendor"
    ADD CONSTRAINT "Vendor_pkey" PRIMARY KEY (id);


--
-- Name: Vendor Vendor_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Vendor"
    ADD CONSTRAINT "Vendor_user_id_key" UNIQUE (user_id);


--
-- Name: AccessToken_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "AccessToken_company_id_idx" ON public."AccessToken" USING btree (company_id);


--
-- Name: AccessToken_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "AccessToken_is_obsolete_idx" ON public."AccessToken" USING btree (is_obsolete);


--
-- Name: BankAccount_bank_used_for_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankAccount_bank_used_for_idx" ON public."BankAccount" USING btree (bank_used_for);


--
-- Name: BankAccount_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankAccount_company_id_idx" ON public."BankAccount" USING btree (company_id);


--
-- Name: BankAccount_is_bank_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankAccount_is_bank_idx" ON public."BankAccount" USING btree (is_bank);


--
-- Name: BankAccount_is_enabled_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankAccount_is_enabled_idx" ON public."BankAccount" USING btree (is_enabled);


--
-- Name: BankAccount_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankAccount_is_obsolete_idx" ON public."BankAccount" USING btree (is_obsolete);


--
-- Name: BankAccount_is_qr_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankAccount_is_qr_idx" ON public."BankAccount" USING btree (is_qr);


--
-- Name: BankAccount_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankAccount_user_id_idx" ON public."BankAccount" USING btree (user_id);


--
-- Name: BankResponse_bank_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankResponse_bank_id_idx" ON public."BankResponse" USING btree (bank_id);


--
-- Name: BankResponse_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankResponse_company_id_idx" ON public."BankResponse" USING btree (company_id);


--
-- Name: BankResponse_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankResponse_is_obsolete_idx" ON public."BankResponse" USING btree (is_obsolete);


--
-- Name: BankResponse_is_used_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankResponse_is_used_idx" ON public."BankResponse" USING btree (is_used);


--
-- Name: BankResponse_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BankResponse_status_idx" ON public."BankResponse" USING btree (status);


--
-- Name: BeneficiaryAccounts_acc_no_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BeneficiaryAccounts_acc_no_idx" ON public."BeneficiaryAccounts" USING btree (acc_no);


--
-- Name: BeneficiaryAccounts_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "BeneficiaryAccounts_user_id_idx" ON public."BeneficiaryAccounts" USING btree (user_id);


--
-- Name: Calculation_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Calculation_company_id_idx" ON public."Calculation" USING btree (company_id);


--
-- Name: Calculation_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Calculation_is_obsolete_idx" ON public."Calculation" USING btree (is_obsolete);


--
-- Name: Calculation_role_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Calculation_role_id_idx" ON public."Calculation" USING btree (role_id);


--
-- Name: Calculation_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Calculation_user_id_idx" ON public."Calculation" USING btree (user_id);


--
-- Name: ChargeBack_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "ChargeBack_company_id_idx" ON public."ChargeBack" USING btree (company_id);


--
-- Name: ChargeBack_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "ChargeBack_is_obsolete_idx" ON public."ChargeBack" USING btree (is_obsolete);


--
-- Name: ChargeBack_payin_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "ChargeBack_payin_id_idx" ON public."ChargeBack" USING btree (payin_id);


--
-- Name: CheckUtrHistory_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "CheckUtrHistory_company_id_idx" ON public."CheckUtrHistory" USING btree (company_id);


--
-- Name: CheckUtrHistory_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "CheckUtrHistory_is_obsolete_idx" ON public."CheckUtrHistory" USING btree (is_obsolete);


--
-- Name: CheckUtrHistory_payin_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "CheckUtrHistory_payin_id_idx" ON public."CheckUtrHistory" USING btree (payin_id);


--
-- Name: Company_contact_no_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Company_contact_no_idx" ON public."Company" USING btree (contact_no);


--
-- Name: Company_email_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Company_email_idx" ON public."Company" USING btree (email);


--
-- Name: Complaints_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Complaints_company_id_idx" ON public."Complaints" USING btree (company_id);


--
-- Name: Complaints_payin_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Complaints_payin_id_idx" ON public."Complaints" USING btree (payin_id);


--
-- Name: Complaints_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Complaints_status_idx" ON public."Complaints" USING btree (status);


--
-- Name: Designation_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Designation_is_obsolete_idx" ON public."Designation" USING btree (is_obsolete);


--
-- Name: Designation_role_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Designation_role_id_idx" ON public."Designation" USING btree (role_id);


--
-- Name: Merchant_code_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Merchant_code_idx" ON public."Merchant" USING btree (code);


--
-- Name: Merchant_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Merchant_company_id_idx" ON public."Merchant" USING btree (company_id);


--
-- Name: Merchant_dispute_enabled_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Merchant_dispute_enabled_idx" ON public."Merchant" USING btree (dispute_enabled);


--
-- Name: Merchant_is_demo_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Merchant_is_demo_idx" ON public."Merchant" USING btree (is_demo);


--
-- Name: Merchant_is_enabled_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Merchant_is_enabled_idx" ON public."Merchant" USING btree (is_enabled);


--
-- Name: Merchant_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Merchant_is_obsolete_idx" ON public."Merchant" USING btree (is_obsolete);


--
-- Name: Merchant_is_test_mode_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Merchant_is_test_mode_idx" ON public."Merchant" USING btree (is_test_mode);


--
-- Name: Merchant_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Merchant_user_id_idx" ON public."Merchant" USING btree (user_id);


--
-- Name: Payin_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payin_company_id_idx" ON public."Payin" USING btree (company_id);


--
-- Name: Payin_currency_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payin_currency_idx" ON public."Payin" USING btree (currency);


--
-- Name: Payin_is_notified_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payin_is_notified_idx" ON public."Payin" USING btree (is_notified);


--
-- Name: Payin_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payin_is_obsolete_idx" ON public."Payin" USING btree (is_obsolete);


--
-- Name: Payin_is_url_expires_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payin_is_url_expires_idx" ON public."Payin" USING btree (is_url_expires);


--
-- Name: Payin_one_time_used_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payin_one_time_used_idx" ON public."Payin" USING btree (one_time_used);


--
-- Name: Payin_sno_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payin_sno_idx" ON public."Payin" USING btree (sno);


--
-- Name: Payin_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payin_status_idx" ON public."Payin" USING btree (status);


--
-- Name: Payout_bank_acc_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payout_bank_acc_id_idx" ON public."Payout" USING btree (bank_acc_id);


--
-- Name: Payout_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payout_company_id_idx" ON public."Payout" USING btree (company_id);


--
-- Name: Payout_currency_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payout_currency_idx" ON public."Payout" USING btree (currency);


--
-- Name: Payout_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payout_is_obsolete_idx" ON public."Payout" USING btree (is_obsolete);


--
-- Name: Payout_merchant_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payout_merchant_id_idx" ON public."Payout" USING btree (merchant_id);


--
-- Name: Payout_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Payout_status_idx" ON public."Payout" USING btree (status);


--
-- Name: ResetDataHistory_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "ResetDataHistory_company_id_idx" ON public."ResetDataHistory" USING btree (company_id);


--
-- Name: ResetDataHistory_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "ResetDataHistory_is_obsolete_idx" ON public."ResetDataHistory" USING btree (is_obsolete);


--
-- Name: ResetDataHistory_payin_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "ResetDataHistory_payin_id_idx" ON public."ResetDataHistory" USING btree (payin_id);


--
-- Name: ResetDataHistory_pre_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "ResetDataHistory_pre_status_idx" ON public."ResetDataHistory" USING btree (pre_status);


--
-- Name: Role_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Role_is_obsolete_idx" ON public."Role" USING btree (is_obsolete);


--
-- Name: Settlement_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Settlement_company_id_idx" ON public."Settlement" USING btree (company_id);


--
-- Name: Settlement_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Settlement_is_obsolete_idx" ON public."Settlement" USING btree (is_obsolete);


--
-- Name: Settlement_method_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Settlement_method_idx" ON public."Settlement" USING btree (method);


--
-- Name: Settlement_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Settlement_status_idx" ON public."Settlement" USING btree (status);


--
-- Name: Settlement_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Settlement_user_id_idx" ON public."Settlement" USING btree (user_id);


--
-- Name: UserHierarchy_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "UserHierarchy_company_id_idx" ON public."UserHierarchy" USING btree (company_id);


--
-- Name: UserHierarchy_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "UserHierarchy_is_obsolete_idx" ON public."UserHierarchy" USING btree (is_obsolete);


--
-- Name: UserHierarchy_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "UserHierarchy_user_id_idx" ON public."UserHierarchy" USING btree (user_id);


--
-- Name: UserOtp_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "UserOtp_user_id_idx" ON public."UserOtp" USING btree (user_id);


--
-- Name: User_code_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "User_code_idx" ON public."User" USING btree (code);


--
-- Name: User_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "User_company_id_idx" ON public."User" USING btree (company_id);


--
-- Name: User_contact_no_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "User_contact_no_idx" ON public."User" USING btree (contact_no);


--
-- Name: User_designation_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "User_designation_id_idx" ON public."User" USING btree (designation_id);


--
-- Name: User_email_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "User_email_idx" ON public."User" USING btree (email);


--
-- Name: User_is_enabled_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "User_is_enabled_idx" ON public."User" USING btree (is_enabled);


--
-- Name: User_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "User_is_obsolete_idx" ON public."User" USING btree (is_obsolete);


--
-- Name: User_role_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "User_role_id_idx" ON public."User" USING btree (role_id);


--
-- Name: User_user_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "User_user_name_idx" ON public."User" USING btree (user_name);


--
-- Name: Vendor_code_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Vendor_code_idx" ON public."Vendor" USING btree (code);


--
-- Name: Vendor_company_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Vendor_company_id_idx" ON public."Vendor" USING btree (company_id);


--
-- Name: Vendor_is_obsolete_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Vendor_is_obsolete_idx" ON public."Vendor" USING btree (is_obsolete);


--
-- Name: Vendor_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "Vendor_user_id_idx" ON public."Vendor" USING btree (user_id);


--
-- Name: idx_access_token_single_active_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_access_token_single_active_session ON public."AccessToken" USING btree (user_id);


--
-- Name: idx_bankhistory_bank_account_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bankhistory_bank_account_id ON public."BankHistory" USING btree (bank_account_id);


--
-- Name: idx_bankhistory_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bankhistory_created_at ON public."BankHistory" USING btree (created_at);


--
-- Name: idx_bankhistory_is_obsolete; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bankhistory_is_obsolete ON public."BankHistory" USING btree (is_obsolete);


--
-- Name: idx_bankresponse_company_bank_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bankresponse_company_bank_created ON public."BankResponse" USING btree (company_id, is_obsolete, bank_id, created_at);


--
-- Name: idx_bankresponse_company_sno; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bankresponse_company_sno ON public."BankResponse" USING btree (company_id, sno);


--
-- Name: idx_bankresponse_created_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bankresponse_created_active ON public."BankResponse" USING btree (created_at DESC);


--
-- Name: idx_bankresponse_sno_active; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bankresponse_sno_active ON public."BankResponse" USING btree (sno DESC);


--
-- Name: idx_bankresponse_utr; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bankresponse_utr ON public."BankResponse" USING btree (utr);


--
-- Name: idx_calculation_company_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calculation_company_date ON public."Calculation" USING btree (company_id, created_at DESC);


--
-- Name: idx_calculation_user_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_calculation_user_date ON public."Calculation" USING btree (user_id, created_at DESC);


--
-- Name: idx_merchant_payout_notify; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_merchant_payout_notify ON public."Merchant" USING btree ((((config -> 'urls'::text) ->> 'payout_notify'::text)));


--
-- Name: idx_notificationrecipients_company_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notificationrecipients_company_id ON public."NotificationRecipients" USING btree (company_id);


--
-- Name: idx_notificationrecipients_notification_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notificationrecipients_notification_id ON public."NotificationRecipients" USING btree (notification_id);


--
-- Name: idx_notifications_company_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_company_id ON public."Notifications" USING btree (company_id);


--
-- Name: idx_notifications_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_user_id ON public."Notifications" USING btree (user_id);


--
-- Name: idx_payin_bank_acc_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payin_bank_acc_id ON public."Payin" USING btree (bank_acc_id);


--
-- Name: idx_payin_company_bankacc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payin_company_bankacc ON public."Payin" USING btree (company_id, bank_acc_id);


--
-- Name: idx_payin_company_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payin_company_created_at ON public."Payin" USING btree (company_id, created_at DESC) WHERE (is_obsolete = false);


--
-- Name: idx_payin_merchant_order_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payin_merchant_order_id ON public."Payin" USING btree (merchant_order_id);


--
-- Name: idx_payout_company_sno; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payout_company_sno ON public."Payout" USING btree (company_id, is_obsolete, sno DESC);


--
-- Name: idx_payout_main_optimized_asc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payout_main_optimized_asc ON public."Payout" USING btree (company_id, is_obsolete, status, sno);


--
-- Name: idx_payout_order_company; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payout_order_company ON public."Payout" USING btree (merchant_order_id, company_id);


--
-- Name: idx_system_settings_is_obsolete; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_system_settings_is_obsolete ON public."SystemSettings" USING btree (is_obsolete);


--
-- Name: idx_system_settings_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_system_settings_key ON public."SystemSettings" USING btree (key);


--
-- Name: idx_user_submitted_utr; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_submitted_utr ON public."Payin" USING btree (user_submitted_utr);


--
-- Name: AccessToken trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."AccessToken" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: BankAccount trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."BankAccount" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: BankResponse trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."BankResponse" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: BeneficiaryAccounts trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."BeneficiaryAccounts" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: Calculation trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."Calculation" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: ChargeBack trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."ChargeBack" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: CheckUtrHistory trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."CheckUtrHistory" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: Complaints trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."Complaints" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: Designation trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."Designation" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: Merchant trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."Merchant" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: Payin trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."Payin" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: Payout trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."Payout" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: ResetDataHistory trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."ResetDataHistory" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: Role trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."Role" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: Settlement trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."Settlement" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: User trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."User" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: UserHierarchy trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."UserHierarchy" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: Vendor trigger_update_timestamp; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trigger_update_timestamp BEFORE UPDATE ON public."Vendor" FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_column();


--
-- Name: AccessToken AccessToken_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AccessToken"
    ADD CONSTRAINT "AccessToken_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: AccessToken AccessToken_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AccessToken"
    ADD CONSTRAINT "AccessToken_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(id);


--
-- Name: BankAccount BankAccount_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BankAccount"
    ADD CONSTRAINT "BankAccount_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: BankAccount BankAccount_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BankAccount"
    ADD CONSTRAINT "BankAccount_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(id);


--
-- Name: BankHistory BankHistory_bank_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BankHistory"
    ADD CONSTRAINT "BankHistory_bank_account_id_fkey" FOREIGN KEY (bank_account_id) REFERENCES public."BankAccount"(id) ON DELETE CASCADE;


--
-- Name: BankResponse BankResponse_bank_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BankResponse"
    ADD CONSTRAINT "BankResponse_bank_id_fkey" FOREIGN KEY (bank_id) REFERENCES public."BankAccount"(id);


--
-- Name: BankResponse BankResponse_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BankResponse"
    ADD CONSTRAINT "BankResponse_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: BeneficiaryAccounts BeneficiaryAccounts_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BeneficiaryAccounts"
    ADD CONSTRAINT "BeneficiaryAccounts_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: BeneficiaryAccounts BeneficiaryAccounts_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BeneficiaryAccounts"
    ADD CONSTRAINT "BeneficiaryAccounts_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public."Role"(id);


--
-- Name: BeneficiaryAccounts BeneficiaryAccounts_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BeneficiaryAccounts"
    ADD CONSTRAINT "BeneficiaryAccounts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(id);


--
-- Name: Calculation Calculation_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Calculation"
    ADD CONSTRAINT "Calculation_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: Calculation Calculation_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Calculation"
    ADD CONSTRAINT "Calculation_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(id);


--
-- Name: ChargeBack ChargeBack_bank_acc_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ChargeBack"
    ADD CONSTRAINT "ChargeBack_bank_acc_id_fkey" FOREIGN KEY (bank_acc_id) REFERENCES public."BankAccount"(id);


--
-- Name: ChargeBack ChargeBack_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ChargeBack"
    ADD CONSTRAINT "ChargeBack_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: ChargeBack ChargeBack_merchant_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ChargeBack"
    ADD CONSTRAINT "ChargeBack_merchant_user_id_fkey" FOREIGN KEY (merchant_user_id) REFERENCES public."User"(id);


--
-- Name: ChargeBack ChargeBack_payin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ChargeBack"
    ADD CONSTRAINT "ChargeBack_payin_id_fkey" FOREIGN KEY (payin_id) REFERENCES public."Payin"(id);


--
-- Name: ChargeBack ChargeBack_vendor_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ChargeBack"
    ADD CONSTRAINT "ChargeBack_vendor_user_id_fkey" FOREIGN KEY (vendor_user_id) REFERENCES public."User"(id);


--
-- Name: CheckUtrHistory CheckUtrHistory_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."CheckUtrHistory"
    ADD CONSTRAINT "CheckUtrHistory_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: CheckUtrHistory CheckUtrHistory_payin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."CheckUtrHistory"
    ADD CONSTRAINT "CheckUtrHistory_payin_id_fkey" FOREIGN KEY (payin_id) REFERENCES public."Payin"(id);


--
-- Name: Complaints Complaints_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Complaints"
    ADD CONSTRAINT "Complaints_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: Complaints Complaints_payin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Complaints"
    ADD CONSTRAINT "Complaints_payin_id_fkey" FOREIGN KEY (payin_id) REFERENCES public."Payin"(id);


--
-- Name: Designation Designation_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Designation"
    ADD CONSTRAINT "Designation_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public."Role"(id);


--
-- Name: Merchant Merchant_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Merchant"
    ADD CONSTRAINT "Merchant_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: Merchant Merchant_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Merchant"
    ADD CONSTRAINT "Merchant_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(id);


--
-- Name: Payin Payin_bank_acc_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Payin"
    ADD CONSTRAINT "Payin_bank_acc_id_fkey" FOREIGN KEY (bank_acc_id) REFERENCES public."BankAccount"(id);


--
-- Name: Payin Payin_bank_response_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Payin"
    ADD CONSTRAINT "Payin_bank_response_id_fkey" FOREIGN KEY (bank_response_id) REFERENCES public."BankResponse"(id);


--
-- Name: Payin Payin_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Payin"
    ADD CONSTRAINT "Payin_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: Payin Payin_merchant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Payin"
    ADD CONSTRAINT "Payin_merchant_id_fkey" FOREIGN KEY (merchant_id) REFERENCES public."Merchant"(id);


--
-- Name: Payout Payout_bank_acc_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Payout"
    ADD CONSTRAINT "Payout_bank_acc_id_fkey" FOREIGN KEY (bank_acc_id) REFERENCES public."BankAccount"(id);


--
-- Name: Payout Payout_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Payout"
    ADD CONSTRAINT "Payout_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: Payout Payout_merchant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Payout"
    ADD CONSTRAINT "Payout_merchant_id_fkey" FOREIGN KEY (merchant_id) REFERENCES public."Merchant"(id);


--
-- Name: ResetDataHistory ResetDataHistory_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ResetDataHistory"
    ADD CONSTRAINT "ResetDataHistory_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: ResetDataHistory ResetDataHistory_payin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ResetDataHistory"
    ADD CONSTRAINT "ResetDataHistory_payin_id_fkey" FOREIGN KEY (payin_id) REFERENCES public."Payin"(id);


--
-- Name: Settlement Settlement_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Settlement"
    ADD CONSTRAINT "Settlement_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: Settlement Settlement_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Settlement"
    ADD CONSTRAINT "Settlement_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(id);


--
-- Name: UserHierarchy UserHierarchy_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserHierarchy"
    ADD CONSTRAINT "UserHierarchy_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: UserHierarchy UserHierarchy_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserHierarchy"
    ADD CONSTRAINT "UserHierarchy_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(id);


--
-- Name: UserOtp UserOtp_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserOtp"
    ADD CONSTRAINT "UserOtp_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(id);


--
-- Name: User User_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: User User_designation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_designation_id_fkey" FOREIGN KEY (designation_id) REFERENCES public."Designation"(id);


--
-- Name: User User_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public."Role"(id);


--
-- Name: Vendor Vendor_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Vendor"
    ADD CONSTRAINT "Vendor_company_id_fkey" FOREIGN KEY (company_id) REFERENCES public."Company"(id);


--
-- Name: Vendor Vendor_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Vendor"
    ADD CONSTRAINT "Vendor_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public."User"(id);


--
-- Name: NotificationRecipients fk_company; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."NotificationRecipients"
    ADD CONSTRAINT fk_company FOREIGN KEY (company_id) REFERENCES public."Company"(id) ON DELETE CASCADE;


--
-- Name: Notifications fk_company; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT fk_company FOREIGN KEY (company_id) REFERENCES public."Company"(id) ON DELETE CASCADE;


--
-- Name: NotificationRecipients fk_notification; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."NotificationRecipients"
    ADD CONSTRAINT fk_notification FOREIGN KEY (notification_id) REFERENCES public."Notifications"(id) ON DELETE CASCADE;


--
-- Name: Notifications fk_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Notifications"
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES public."User"(id) ON DELETE CASCADE;


-- PostgreSQL database dump complete