name: Deploying to EC2

on:
  push:
    branches:
      - trust-pay-stg

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        TARGET_DIR: ${{ secrets.TARGET_DIR }}
      run: |
        # Write the SSH key to a file
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key

        # SSH into EC2 and deploy with debug output
        ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << 'EOF'
          cd $TARGET_DIR  # Use the TARGET_DIR variable
          echo "Current directory: $(/bin/pwd)" 
          git status  # Debug: Show Git state
          git pull origin trust-pay-stg
          npm install
          pm2 restart all
        EOF

        # Clean up
        rm -f private_key